In [1]:
import numpy as np

#problem 1

a1 = np.empty((2,2))
print("1. Empty 2x2 array:\n", a1, "\n")

a2 = np.ones((4,2))
print("2. Ones 4x2 array:\n", a2, "\n")

a3 = np.full((2,2), 4)  
print("3. Full array (2x2 filled with 4):\n", a3, "\n")

ref = np.array([[1,2,3],[4,5,6]])
a4 = np.zeros_like(ref)
print("4. zeros_like(ref):\n", a4, "\n")

a5 = np.ones_like(ref)
print("5. ones_like(ref):\n", a5, "\n")

new_list = [1,2,3,4]
a6 = np.array(new_list)
print("6. Converted numpy array:\n", a6)

1. Empty 2x2 array:
 [[6.37401647e-067 2.16847421e-028]
 [1.21403156e-312 1.31318852e-311]] 

2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

3. Full array (2x2 filled with 4):
 [[4 4]
 [4 4]] 

4. zeros_like(ref):
 [[0 0 0]
 [0 0 0]] 

5. ones_like(ref):
 [[1 1 1]
 [1 1 1]] 

6. Converted numpy array:
 [1 2 3 4]


In [2]:
import numpy as np

#problem 2

p1 = np.arange(10, 50)
print("1:\n", p1, "\n")

p2 = np.arange(9).reshape(3,3)
print("2:\n", p2, "\n")

p3 = np.eye(3)
print("3:\n", p3, "\n")

r = np.random.random(30)
print("4 array:\n", r)
print("4 mean:", r.mean(), "\n")

r2 = np.random.random((10,10))
print("5 min:", r2.min())
print("5 max:", r2.max(), "\n")

p6 = np.zeros(10)
p6[4] = 1
print("6:\n", p6, "\n")

arr = np.array([1,2,0,0,4,0])
rev = arr[::-1]
print("7:\n", rev, "\n")

p8 = np.ones((5,5))
p8[1:-1, 1:-1] = 0
print("8:\n", p8, "\n")

p9 = np.zeros((8,8))
p9[::2, 1::2] = 1
p9[1::2, ::2] = 1
print("9:\n", p9)

1:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4 array:
 [0.21859577 0.7762775  0.91666409 0.87521707 0.37765734 0.465923
 0.9975324  0.06704575 0.92791625 0.90787088 0.14079773 0.77320046
 0.52550937 0.2088931  0.84455966 0.80137628 0.3235934  0.15211265
 0.34892871 0.22221619 0.36844409 0.64725245 0.1961091  0.9586547
 0.0288774  0.65515608 0.2134275  0.13239913 0.69318172 0.59343355]
4 mean: 0.5119607775545343 

5 min: 0.014457383766529053
5 max: 0.9958696430203776 

6:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 

7:
 [0 4 0 0 2 1] 

8:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] 

9:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0

In [3]:
#problem 3
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

add_xy = x + y
print("1:\n", add_xy, "\n")

sub_xy = x - y
print("2:\n", sub_xy, "\n")

mul = x * 3
print("3:\n", mul, "\n")

sq = x ** 2
print("4:\n", sq, "\n")

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("5 dot(v,w):", dot_vw)
print("5 dot(x,v):", dot_xv)
print("5 dot(x,y):\n", dot_xy, "\n")

concat_xy_row = np.concatenate((x, y), axis=0)
print("6 concat x,y row:\n", concat_xy_row)

concat_vw_col = np.vstack((v, w))
print("\n6 concat v,w col:\n", concat_vw_col, "\n")

try:
    test = np.concatenate((x, v))
except Exception as e:
    print("7 ERROR explanation:")
    print("x shape =", x.shape)
    print("v shape =", v.shape)
    print("Reason: Cannot concatenate a 2D array (2x2) with a 1D array (2,).")

1:
 [[ 6  8]
 [10 13]] 

2:
 [[-4 -4]
 [-4 -3]] 

3:
 [[ 3  6]
 [ 9 15]] 

4:
 [[ 1  4]
 [ 9 25]] 

5 dot(v,w): 219
5 dot(x,v): [29 77]
5 dot(x,y):
 [[19 22]
 [50 58]] 

6 concat x,y row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

6 concat v,w col:
 [[ 9 10]
 [11 12]] 

7 ERROR explanation:
x shape = (2, 2)
v shape = (2,)
Reason: Cannot concatenate a 2D array (2x2) with a 1D array (2,).


In [4]:
#problem 4
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inv = np.linalg.inv(A)       
I = np.dot(A, A_inv)             
print("A * A^-1 =\n", I)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB =\n", AB)
print("BA =\n", BA)
print("AB == BA ?", np.array_equal(AB, BA))

AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T =\n", AB_T)
print("B^T * A^T =\n", BT_AT)
print("(AB)^T == B^T * A^T ?", np.array_equal(AB_T, BT_AT))


coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])

B_vector = np.array([-1, -3, 9])

X = np.dot(np.linalg.inv(coeff_matrix), B_vector)
print("\nSolution for [x, y, z] =", X)

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA ? False

(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
(AB)^T == B^T * A^T ? True

Solution for [x, y, z] = [ 2.  1. -2.]
